spring:
  ai:
    vertex:
      ai:
        gemini:
          api-key: ${GEMINI_API_KEY}
          project-id: "gen-lang-client-0980652047" # GCP 프로젝트 ID
          location: "us-central1"
          chat:
            options:
              model: "gemini-2.5-flash" # 사용할 Gemini 모델명